name: Badgerblog
favicon: null
layout_spectrum: 0.9409452674444765
typography_spectrum: 0.7560835594777018
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#3C493F'
    - '#7E8D85'
    - '#B3BFB8'
    - '#F0F7F4'
    - '#A2E3C4'
  brandStrength: 0.9842481042724103
  lightness: 0.18576618819497526
  saturation: 0.6760174364317209
  rhythmicContrast: 0.784939389443025
purpose: []
