analytics: {}
color:
  brandColors:
    - '#000000'
    - '#185010'
    - '#000000'
    - '#C8D090'
    - '#C8E888'
  brandStrength: 0.365991
  lightness: 0.350225
  rhythmicContrast: 0
  saturation: 0.1875
cta: {}
layout_spectrum: 1
name: Badgerblog
opengraph: {}
purpose: []
typography_spectrum: 0.532657
