name: Badgerblog
favicon: null
layout_spectrum: 0.87871
typography_spectrum: 0.14728
title: jennes blog
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#d08700'
    - '#321400'
    - '#007700'
    - '#924e0c'
  brandStrength: 1
  lightness: 0.625
  saturation: 0.1875
  rhythmicContrast: 0.5
purpose: []
